#application.yml
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: uat
---

spring:
  application:
    name: template
  main:
    banner-mode : off
    sources : com.turborvip.core
  output:
    ansi:
      enabled: ALWAYS
  graphql:
    graphiql:
      enabled: true